# Generated by Django 4.2 on 2026-09-25 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('photo', models.URLField(blank=True)),
                ('location', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('address_ar', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=32)),
                ('operating_hours', models.CharField(max_length=128)),
                ('operating_hours_ar', models.CharField(blank=True, max_length=128)),
                ('about', models.TextField()),
                ('about_ar', models.TextField(blank=True)),
                ('emergency_available', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated')], db_index=True, default='Active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_facility', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'db_table': 'meetadr_hospitals',
            },
        ),
        migrations.CreateModel(
            name='FacilityDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('head_of_department', models.CharField(blank=True, max_length=255)),
                ('bed_capacity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='facilities.hospital')),
            ],
            options={
                'verbose_name': 'Facility Department',
                'verbose_name_plural': 'Facility Departments',
                'db_table': 'meetadr_facility_departments',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('photo', models.URLField(blank=True)),
                ('location', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('address_ar', models.TextField(blank=True)),
                ('primary_specialty', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=32)),
                ('operating_hours', models.CharField(max_length=128)),
                ('operating_hours_ar', models.CharField(blank=True, max_length=128)),
                ('about', models.TextField()),
                ('about_ar', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated')], db_index=True, default='Active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinic_facility', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
                'db_table': 'meetadr_clinics',
            },
        ),
    ]
