# Generated by Django 4.2 on 2026-10-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='insurance_plans',
            field=models.TextField(blank=True, help_text='Comma-separated list of accepted insurance providers'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='insurance_plans',
            field=models.TextField(blank=True, help_text='Comma-separated list of accepted insurance providers'),
        ),
    ]
