# Generated by Django 4.2 on 2026-09-25 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prescription', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'db_table': 'meetadr_prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(help_text='e.g. 500 mg', max_length=128)),
                ('frequency', models.CharField(help_text='e.g. Twice daily after meals', max_length=128)),
                ('duration', models.CharField(help_text='e.g. 7 days', max_length=128)),
                ('instructions', models.TextField(blank=True, help_text='Specific usage directions')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Medication',
                'verbose_name_plural': 'Prescription Medications',
                'db_table': 'meetadr_prescription_medications',
            },
        ),
    ]
