# Generated by Django 4.2 on 2026-09-25 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic')], db_index=True, max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(default='United Arab Emirates', max_length=64)),
                ('location', models.CharField(max_length=128)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_provider_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Request',
                'verbose_name_plural': 'Provider Requests',
                'db_table': 'meetadr_provider_requests',
            },
        ),
        migrations.CreateModel(
            name='ProviderInvitationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Invitation Token',
                'verbose_name_plural': 'Provider Invitation Tokens',
                'db_table': 'meetadr_provider_invitation_tokens',
            },
        ),
    ]
