# Generated by Django 4.2 on 2026-09-28 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerrequest',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_requests', to='facilities.clinic'),
        ),
        migrations.AddField(
            model_name='providerrequest',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_requests', to='facilities.hospital'),
        ),
    ]
