# Generated by Django 4.2 on 2026-09-25 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('photo', models.URLField(blank=True)),
                ('specialty', models.CharField(db_index=True, max_length=128)),
                ('special_interests', models.JSONField(blank=True, default=list)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('experience_text', models.CharField(blank=True, max_length=64)),
                ('experience_text_ar', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(max_length=128)),
                ('about', models.TextField(blank=True)),
                ('about_ar', models.TextField(blank=True)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated')], db_index=True, default='Active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='facilities.clinic')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='facilities.hospital')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'meetadr_doctors',
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_days', models.JSONField(default=list, help_text="List of active weekdays, e.g. ['Monday', 'Tuesday', 'Wednesday']")),
                ('standard_slots', models.JSONField(default=list, help_text="List of active consultation intervals, e.g. ['09:00 - 09:30', '09:30 - 10:00']")),
                ('slot_duration_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Schedule',
                'verbose_name_plural': 'Doctor Schedules',
                'db_table': 'meetadr_doctor_schedules',
            },
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('clinic__isnull', True), ('hospital__isnull', False)), models.Q(('clinic__isnull', False), ('hospital__isnull', True)), _connector='OR'), name='doctor_must_belong_to_hospital_xor_clinic'),
        ),
    ]
