# Generated by Django 4.2 on 2026-10-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='doctor',
            name='doctor_must_belong_to_hospital_xor_clinic',
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.CheckConstraint(check=models.Q(('hospital__isnull', True), ('clinic__isnull', True), _connector='OR'), name='doctor_cannot_belong_to_both_hospital_and_clinic'),
        ),
    ]
