# Generated by Django 4.2 on 2026-09-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doctorreview',
            index=models.Index(fields=['doctor', '-created_at'], name='rev_doc_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctorreview',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='doctor_review_rating_1_to_5'),
        ),
    ]
