# Generated by Django 4.2 on 2026-10-02 06:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0002_doctorreview_rev_doc_created_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facility_review', to='appointments.appointment')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='facilities.clinic')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='facilities.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facility_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility Review',
                'verbose_name_plural': 'Facility Reviews',
                'db_table': 'meetadr_facility_reviews',
            },
        ),
        migrations.AddIndex(
            model_name='facilityreview',
            index=models.Index(fields=['hospital', '-created_at'], name='rev_hosp_created_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityreview',
            index=models.Index(fields=['clinic', '-created_at'], name='rev_clinic_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='facilityreview',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='facility_review_rating_1_to_5'),
        ),
        migrations.AddConstraint(
            model_name='facilityreview',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('clinic__isnull', True), ('hospital__isnull', False)), models.Q(('clinic__isnull', False), ('hospital__isnull', True)), _connector='OR'), name='facility_review_hospital_xor_clinic'),
        ),
    ]
